server:
  port: 8088

fiap:
  debug: false


spring:
  datasource:
    url: jdbc:h2:C:\Users\sheldon.gomes.ALCNET\Documents\h2;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springfox:
  documentation:
    swagger-ui:
      enabled: true
