create table tb_product
(
    id               bigint generated by default as identity,
    ativo            boolean,
    cor              varchar(255),
    data_atualizacao timestamp,
    data_criacao     timestamp not null,
    modelo           varchar(255),
    numero           integer,
    preco            decimal(19, 2),
    primary key (id)
)